/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'imageUrl' : string,
  'caption' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'price' : bigint,
}
export interface Section { 'id' : bigint, 'title' : string, 'content' : string }
export interface SiteSettings { 'siteName' : string, 'logoUrl' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'addProduct' : ActorMethod<
    [string, string, bigint, string, [] | [string]],
    undefined
  >,
  'adminLogin' : ActorMethod<[string, string], [] | [string]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSection' : ActorMethod<[string, string, [] | [string]], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint, [] | [string]], undefined>,
  'deleteMessage' : ActorMethod<[bigint, [] | [string]], undefined>,
  'deleteProduct' : ActorMethod<[bigint, [] | [string]], undefined>,
  'deleteSection' : ActorMethod<[bigint, [] | [string]], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getGallery' : ActorMethod<[], Array<GalleryItem>>,
  'getMessages' : ActorMethod<[[] | [string]], Array<ContactMessage>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSections' : ActorMethod<[], Array<Section>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'health' : ActorMethod<[], string>,
  'initializeContent' : ActorMethod<[[] | [string]], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string, string], undefined>,
  'updateContactInfo' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [bigint, string, string, string, [] | [string]],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, string, [] | [string]],
    undefined
  >,
  'updateSection' : ActorMethod<
    [bigint, string, string, [] | [string]],
    undefined
  >,
  'updateSiteSettings' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];