/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});
export const Section = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const SiteSettings = IDL.Record({
  'siteName' : IDL.Text,
  'logoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSection' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'deleteSection' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getMessages' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(ContactMessage)], []),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'health' : IDL.Func([], [IDL.Text], ['query']),
  'initializeContent' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateContactInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateGalleryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateSection' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateSiteSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Section = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const SiteSettings = IDL.Record({
    'siteName' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSection' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'deleteSection' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(ContactMessage)],
        [],
      ),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSections' : IDL.Func([], [IDL.Vec(Section)], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'health' : IDL.Func([], [IDL.Text], ['query']),
    'initializeContent' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateContactInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateGalleryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSection' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateSiteSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };